### ISSUE TITLE
automatic discard of replacement Cerulean Potion and Kitsune's Gift rewards if full inv. - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#675]
Replacement Cerulean Potions and Kisune's Gift rewards are automatically discarded if inventory is full. The suitable text containing "You may replace the contents of a pouch with *item* or abandon it." is displayed but only the "Next" button is presented. The two situations may be related.

To reproduce:
obtain and drink a Cerulean Potion
fill all empty inventory slots
go to sleep and meet cerulean succubus
-or-
obtain 2 or more Kitsune's Gift
fill all empty inventory slots
open gifts without letting the gift slot become empty

**Comment by IndirectOne** [comment]
Right - fix submitted. Funny, because I thought I tested those two cases. I knew they were trouble, along with Reducto, GrowPlus and a few others.

Turns out there were separate causes. The cerulean encounter had an extra doNext(campMenu) at the end which overrode the takeItem menu.
The Kitsune Gift needed to be changed so that it could tell the inventory not to override its menu. Good news is that doing that cleaned up Reducto and GroPlus very slightly.
