### ISSUE TITLE
Essrayle causing 'end of lactation' notifications even when not causing lactation - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#680]
Feeding Essrayle with a breasted PC but not permitting her to augment said breasts triggers a "Your breasts no longer produce any milk." message after several hours even though no lactation was caused. The PC in question was hermaphroditic.

to reproduce:
have breasts
meet Essrayle
allow her to feed but not to adjust PC's breasts
wait

**Comment by IndirectOne** [comment]
Should now be fixed.

**Comment by tmedwards** [comment]
As long as you agree to feed her, Essrayle pumps the PCs breasts regardless of whether you allow her to expand them, thus milking them if the PC is lactating.  Your patch completely breaks this.

The proper fix would have been to simply add a lactation check to the Feeder reset and lactation boost block, rather than moving it into the BE reward block.  For example:
```ActionScript
		/*  BE reward block */
	}
	if (player.biggestTitSize() >= 1 && player.isLactating()) {
		if (player.findStatusAffect(StatusAffects.Feeder) >= 0) {
			player.addStatusValue(StatusAffects.Feeder,1,1);
			player.changeStatusValue(StatusAffects.Feeder,2,0);
		}
		player.boostLactation(0.01);
	}
	player.orgasm();
```

Though, updating the code probably wouldn't be a bad idea either.  For example:
```ActionScript
		/*  BE reward block */
	}
	if (player.hasBreasts() && player.isLactating()) {
		player.milked();
		player.boostLactation(0.01);
	}
	player.orgasm();
```

**Comment by IndirectOne** [comment]
Thanks. I'm sending in another pull request that copies your correction. That does explain why the Feeder stuff was outside the BE block. I assumed it was part of that.
