### ISSUE TITLE
Need Help understand Terms

### ISSUE THREAD

**Issue by Korvas** [herp-a-derp/Corruption-of-Champions#724]
Hi all, I have a question. I downloaded the most recent version of CoC's source code and saw that many things have changed. Some of it I figured out, but a lot of it doesn't make any sense to me. what is args? What is eventParser, what is timeQ and campQ, what does rand do? There are so many new terms and I'm unfamiliar in their usage

**Comment by Frahuenheld** [comment]
Hi, I'm just comenting to tell you to be patient until @IndirectOne comes back.
Your other option is to go to the blog and ask Fenoxo in the comments and pray for him or someone else to see you.

**Comment by Korvas** [comment]
Hey, thanks for answering. I have been waiting patiently and I did ask on the forums though they weren't any help there. They basically said the whole thing was impossible to understand and that I should start over

**Comment by herp-a-derp** [comment]
I'm not sure what you're expecting here.

What the various functions do is largely self-explanatory, and you have the source. If you want to know what `eventParser` does, *just read the source for event parser*. 

There are no new "terms", there are certainly new functions, and variables, and things have moved around, but it's still actionscript.

**Comment by Korvas** [comment]
Well, I just need help understand them. I mean, I look for the terms on the web and turn up nothing, not even a situation where they would be used. Most of what I'm learning is through experimentation and trial and error.

**Comment by IndirectOne** [comment]
I didn't expect to be gone so long. I've been working on more Kath stuff, plus some RL stuff and I didn't want to add bug fixes while dealing with that.

As to what the various functions do I'd recommend downloading Windows Grep or some similar program so you can search the whole code base to see where the function gets used.

The basic layout of how CoC works is the same - at the end of every chain of functions there is a call to menu() + addButton(), doNext(), doYesNo, choices() or simpleChoices(). Those provide the choices for the user. In old code they chose by accepting a number which would then get passed to eventParser(). eventParser() would lookup that number code and call a particular function. Newer code does not do this, instead the actual function name gets passed to those functions. This is better because it's easier to understand what's going on.
