### ISSUE TITLE
dbl pepper calls wrong cock descriptor when growing new cock - 0.9.4c

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#757]
character with one lizard cock received this message when growing a new cock

"You feel something slippery wiggling inside your sheath, and another red point peeks out. In spite of yourself, you start getting turned on by the change, and the new dick slowly slides free, eventually stopping once the thick knot pops free. The pair of dog-dicks hang there, leaking pre-cum and arousing you far beyond normal.

Your crotch twitches, and you pull open your crotch-hugging slutty swimwear to get a better look. You watch in horror and arousal as your canine[refers to existing cock; should be lizard] cock warps and twists, becoming red and pointed, just like other dog-dick, growing thick bulges near the base. When it stops you have two dog-cocks and an animal-like sheath. The whole episode turns you on far more than it should, leaving you dripping animal pre and ready to breed."

**Comment by ambjoorn94** [comment]
That's strange... according to the code, this text should only appear with the conditions:
if (type == 2) // Double Pepper
if !(player.dogCocks() >= 2)
if !(player.dogCocks() == 0)
meaning that the character would need to have exactly 1 dog or fox cock... or a negative amount, but I doubt that could happen...

Debugging might be necessary to see exactly how this could have happened, since I can't seem to be able to figure out how

**Comment by Gedan** [comment]
Yeah, you would have had to have already had an existing canine-type donger for that to happen. If you only had _one_ cock and it was a lizard cock, then, well uh I dunno what to say.

I just tested it with a character set up like that and it seems to work fine soooo short of getting a save that can trigger it, not much else I can really do.
