### ISSUE TITLE
Latex girl screen blank after giving Incubus draft

### ISSUE THREAD

**Issue by AuthenticTeddy** [herp-a-derp/Corruption-of-Champions#769]
After giving the latex girl an incubus draft, clicking on her just spawns a blank page at the slaves menu

**Comment by Gedan** [comment]
Works fine with my test character. Will need a save to investigate further.

**Comment by ankser** [comment]
[CoC_4.sol.gz.zip](https://github.com/herp-a-derp/Corruption-of-Champions/files/157406/CoC_4.sol.gz.zip)

Same here, affected not only latex girl, but some masturbations scenes too.

**Comment by ambjoorn94** [comment]
According to my investigations, it seems this bug does not happen when giving minotaur blood firstmost.

My guess is that the problem lies in the function on line 688 always changing kFLAGS.GOO_DICK_LENGTH but not changing kFLAGS.GOO_DICK_TYPE unless fed consumables.MINOBLO aka Minotaur blood the first time.

The above would in turn cause an error in line 550, where it checks if kFLAGS.GOO_DICK_LENGTH is larger than 0, and then tries to get the cock type, which doesn't exist unless fed minoblood.

The suggested fix would be to change the function at line 688 to set a value to kFLAGS.GOO_DICK_TYPE for each type of item.

**Comment by StarController** [comment]
I encountered this issue the other day on the ipad version.  Assuming ambjoorn94's fix works as advertised, will this be folded in for the next release that Fen teased on his site today (3/18)?

**Comment by Gedan** [comment]
If the type has been unset, then accessing the flag value will return 0. Ergo, the type should be coming back out of gooGetCockType() should be CockTypesEnum.HUMAN. Which, granted, is still not correct, but it should *work* rather than cause random issues.

**Comment by ambjoorn94** [comment]
The issue seems to have been lifted by some commit between versions 0.9.4c and 1.0.2
