### ISSUE TITLE
no morning sex choices in Sheila's overnight camping - 0.9.4c

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#784]
After knocking up Sheila and encountering her birth announcement late at night (20:00), the player has the option to spend the night camping in the field with her -- high-libido characters are supposed to be offered sex choices during the morning after scene, but the only option that appears in the menu is 'LeaveHerBe', the decline option.

**Comment by ambjoorn94** [comment]
Libido seems to be irrelevant. The relevant stat would be lust. However, since you see the 'LeaveHerBe' button, you should be able to see at least the Masturbation option.

OK, after searching for a bit, it seems like a misplaced menu(); call cleared those other options.
Hopefully it will fix this issue.

**Comment by Zeikfried** [comment]
You're right, actually. I did tie it to lust in this scene.

From the Sheila doc:

end scene if lust <30, else add minor lib-based lust damage and display choices for consensual sex plus [Leave Her Be]
