### ISSUE TITLE
PC permanently Urta

### ISSUE THREAD

**Issue by zerocool123** [herp-a-derp/Corruption-of-Champions#817]
Started the fertility questline, and forgot to save before. So before clicking to start, I hit data and saved content. Took me back to camp, and now my PC is Urta, and I can't travel to any towns or finish off the quest line. Would prefer not to have to start entirely over, but looks like it might be the only option.

**Comment by Ultimaximus** [comment]
I found that too. Turns out, you can use Explore to re-find everything, including Tel'Adre, where you meet... Urta. As Urta, you can then have sex with Urta, or talk to her about her infertility, sending her on a quest, where you can repeat the glitch (the Data button is available during the initial scenes before she embarks).

It's actually a glitch with the Data menu. No need to save, if you enter and exit the Data menu, then you're taken out of whatever cutscene you're in. For example, I can go get captured by the basilisks in the stronghold, meet Jean-Claude, and rather than Taunt or Run, I can enter and exit the Data menu, and then be back at the tunnel entrance where I can just proceed to the Stronghold.
